# Generated by Django 4.2.16 on 2024-12-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Randomaizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.CharField(max_length=30)),
            ],
        ),
    ]
